// examples/02-react/app.tsx
import React, {useEffect, useMemo, useState} from 'react';
import {Map} from 'react-map-gl/maplibre';
import DeckGL from '@deck.gl/react';
import {Filter, vectorTableSource} from '@carto/api-client';
import {
  CategoryWidget,
  FormulaWidget,
  HistogramWidget,
  PieWidget,
  ScatterWidget,
  TableWidget,
} from '../components/index-react.js';
import {MapView} from '@deck.gl/core';
import {VectorTileLayer} from '@deck.gl/carto';
import {FilterEvent} from '../components/types.js';

const MAP_VIEW = new MapView({repeat: true});
const MAP_STYLE =
  'https://basemaps.cartocdn.com/gl/positron-nolabels-gl-style/style.json';
const INITIAL_VIEW_STATE = {latitude: 40.7128, longitude: -74.006, zoom: 12};

export function App(): JSX.Element {
  const [viewState, setViewState] = useState({...INITIAL_VIEW_STATE});
  const [filters, setFilters] = useState<Record<string, Filter>>({});
  const [attributionHTML, setAttributionHTML] = useState('');

  // Update sources.
  const data = useMemo(() => {
    return vectorTableSource({
      accessToken: import.meta.env.VITE_CARTO_ACCESS_TOKEN,
      connectionName: 'carto_dw',
      tableName: 'carto-demo-data.demo_tables.retail_stores',
      filters,
    });
  }, [filters]);

  // Update layers.
  const layers = useMemo(() => {
    return [
      new VectorTileLayer({
        id: 'retail_stores',
        data,
        pointRadiusMinPixels: 4,
        getFillColor: [200, 0, 80],
      }),
    ];
  }, [data]);

  useEffect(() => {
    data?.then(({attribution}) => setAttributionHTML(attribution));
  }, [data]);

  return (
    <>
      <header>
        <h1>React</h1>
        <a href="../">← Back</a>
      </header>
      <section id="view">
        <DeckGL
          layers={layers}
          views={MAP_VIEW}
          initialViewState={INITIAL_VIEW_STATE}
          controller={{dragRotate: false}}
          onViewStateChange={({viewState}) => setViewState(viewState)}
        >
          <Map reuseMaps mapStyle={MAP_STYLE} />
        </DeckGL>
      </section>
      <section id="rail">
        <FormulaWidget
          data={data}
          viewState={viewState}
          header="Total"
          operation="count"
        ></FormulaWidget>

        <CategoryWidget
          data={data}
          viewState={viewState}
          header="Store type"
          operation="count"
          column="storetype"
          onfilter={(e) => setFilters((e as FilterEvent).detail.filters)}
        ></CategoryWidget>

        <PieWidget
          data={data}
          viewState={viewState}
          header="Store type"
          operation="count"
          column="storetype"
          onfilter={(e) => setFilters((e as FilterEvent).detail.filters)}
        ></PieWidget>

        <TableWidget
          data={data}
          viewState={viewState}
          header="Store type"
          columns={['storetype', 'revenue']}
          sortBy="revenue"
        ></TableWidget>

        <ScatterWidget
          data={data}
          viewState={viewState}
          header="Size vs. Revenue"
          xAxisColumn="size_m2"
          yAxisColumn="revenue"
        ></ScatterWidget>

        <HistogramWidget
          data={data}
          viewState={viewState}
          header="Revenue"
          column="revenue"
          ticks={[1250000, 1500000, 1750000]}
        ></HistogramWidget>
      </section>
      <footer
        id="footer"
        dangerouslySetInnerHTML={{__html: attributionHTML}}
      ></footer>
    </>
  );
}

// examples/04-vue/app.vue
<script setup lang="ts">
import '../components/index.js';
import {FilterEvent} from '../components/index.js';
import {Filter, vectorTableSource} from '@carto/api-client';
import {Map} from 'maplibre-gl';
import {Deck, MapViewState} from '@deck.gl/core';
import {VectorTileLayer} from '@deck.gl/carto';
import {
  computed,
  onMounted,
  onUnmounted,
  ref,
  shallowRef,
  watchEffect,
} from 'vue';

const ACCESS_TOKEN = import.meta.env.VITE_CARTO_ACCESS_TOKEN;
const MAP_STYLE =
  'https://basemaps.cartocdn.com/gl/positron-nolabels-gl-style/style.json';
const INITIAL_MAP_STATE: MapViewState = {
  latitude: 40.7128,
  longitude: -74.006,
  zoom: 12,
};

const map = shallowRef<Map | null>(null);
const deck = shallowRef<Deck | null>(null);
const viewState = ref<MapViewState>(INITIAL_MAP_STATE);
const filters = ref<Record<string, Filter>>({});
const attributionHTML = ref<string>('');

const data = computed(() =>
  vectorTableSource({
    accessToken: ACCESS_TOKEN,
    connectionName: 'carto_dw',
    tableName: 'carto-demo-data.demo_tables.retail_stores',
    filters: filters.value,
  })
);

const layer = computed(
  () =>
    new VectorTileLayer({
      id: 'retail_stores',
      data: data.value,
      pointRadiusMinPixels: 4,
      getFillColor: [200, 0, 80],
    })
);

watchEffect(() => {
  const {longitude, latitude, ...rest} = viewState.value;
  map.value?.jumpTo({center: [longitude, latitude], ...rest});
});

watchEffect(() => {
  deck.value?.setProps({layers: layer.value ? [layer.value] : []});
});

watchEffect(() => {
  data.value?.then(({attribution}) => (attributionHTML.value = attribution));
});

function onFilterChange(event: FilterEvent) {
  filters.value = event.detail.filters;
}

onMounted(() => {
  map.value = new Map({
    container: 'map',
    style: MAP_STYLE,
    interactive: false,
  });

  deck.value = new Deck({
    canvas: 'deck-canvas',
    initialViewState: INITIAL_MAP_STATE,
    controller: true,
    layers: [],
    onViewStateChange: ({viewState: _viewState}) => {
      viewState.value = _viewState;
    },
  });
});

onUnmounted(() => {
  deck.value?.finalize();
  map.value?.remove();
});
</script>

<template>
  <header>
    <h1>Vue</h1>
    <a href="../">← Back</a>
  </header>
  <section id="view">
    <div id="map"></div>
    <canvas id="deck-canvas"></canvas>
  </section>
  <section id="rail">
    <formula-widget
      header="Total"
      operation="count"
      :data="data"
      :viewState="viewState"
    ></formula-widget>

    <category-widget
      header="Store type"
      operation="count"
      column="storetype"
      :data="data"
      :viewState="viewState"
      @filter="onFilterChange"
    ></category-widget>

    <pie-widget
      header="Store type"
      operation="count"
      column="storetype"
      :data="data"
      :viewState="viewState"
      @filter="onFilterChange"
    ></pie-widget>

    <table-widget
      header="Store type"
      :columns="['storetype', 'revenue']"
      sortBy="revenue"
      :data="data"
      :viewState="viewState"
    ></table-widget>

    <scatter-widget
      header="Size vs. Revenue"
      xAxisColumn="size_m2"
      yAxisColumn="revenue"
      :data="data"
      :viewState="viewState"
    ></scatter-widget>

    <histogram-widget
      header="Revenue"
      column="revenue"
      :ticks="[1250000, 1500000, 1750000]"
      :data="data"
      :viewState="viewState"
    ></histogram-widget>
  </section>
  <footer id="footer" v-html="attributionHTML"></footer>
</template>

<style scoped></style>
